export const keys = [
  { position: 1, name: 'C4', key: 'Tab', height: 1 },
  { position: 1.5, name: 'C#4', key: '1', height: 0.8 },
  { position: 2, name: 'D4', key: 'q', height: 1 },
  { position: 2.5, name: 'D#4', key: '2', height: 0.8 },
  { position: 3, name: 'E4', key: 'w', height: 1 },
  { position: 4, name: 'F4', key: 'e', height: 1 },
  { position: 4.5, name: 'F#4', key: '4', height: 0.8 },
  { position: 5, name: 'G4', key: 'r', height: 1 },
  { position: 5.5, name: 'G#4', key: '5', height: 0.8 },
  { position: 6, name: 'A4', key: 't', height: 1 },
  { position: 6.5, name: 'A#4', key: '6', height: 0.8 },
  { position: 7, name: 'B4', key: 'y', height: 1 },
  { position: 8, name: 'C5', key: 'u', height: 1 },
  { position: 8.5, name: 'C#5', key: '8', height: 0.8 },
  { position: 9, name: 'D5', key: 'i', height: 1 },
  { position: 9.5, name: 'D#5', key: '9', height: 0.8 },
  { position: 10, name: 'E5', key: 'o', height: 1 },
  { position: 11, name: 'F5', key: 'p', height: 1 },
  { position: 11.5, name: 'F#5', key: '-', height: 0.8 },
  { position: 12, name: 'G5', key: '[', height: 1 },
  { position: 12.5, name: 'G#5', key: '=', height: 0.8 },
  { position: 13, name: 'A5', key: ']', height: 1 },
  { position: 13.5, name: 'A#5', key: '\\', height: 0.8 },
  { position: 14, name: 'B5', key: 'Enter', height: 1 },
];
