export const keys = [
  { id: 0, name: 'C4', key: 'Tab', height: 1 },
  { id: 1, name: 'C#4', key: '1', height: 0.8 },
  { id: 2, name: 'D4', key: 'q', height: 1 },
  { id: 3, name: 'D#4', key: '2', height: 0.8 },
  { id: 4, name: 'E4', key: 'w', height: 1 },
  { id: 5, name: 'F4', key: 'e', height: 1 },
  { id: 6, name: 'F#4', key: '4', height: 0.8 },
  { id: 7, name: 'G4', key: 'r', height: 1 },
  { id: 8, name: 'G#4', key: '5', height: 0.8 },
  { id: 9, name: 'A4', key: 't', height: 1 },
  { id: 10, name: 'A#4', key: '6', height: 0.8 },
  { id: 11, name: 'B4', key: 'y', height: 1 },
  { id: 12, name: 'C5', key: 'u', height: 1 },
  { id: 13, name: 'C#5', key: '8', height: 0.8 },
  { id: 14, name: 'D5', key: 'i', height: 1 },
  { id: 15, name: 'D#5', key: '9', height: 0.8 },
  { id: 16, name: 'E5', key: 'o', height: 1 },
  { id: 17, name: 'F5', key: 'p', height: 1 },
  { id: 18, name: 'F#5', key: '-', height: 0.8 },
  { id: 19, name: 'G5', key: '[', height: 1 },
  { id: 20, name: 'G#5', key: '=', height: 0.8 },
  { id: 21, name: 'A5', key: ']', height: 1 },
  { id: 22, name: 'A#5', key: '\\', height: 0.8 },
  { id: 23, name: 'B5', key: 'Enter', height: 1 },
];
